# JWT
JWT_SECRET_KEY = "JWT_SECRET_KEY"
JWT_HEADER_TYPE = "JWT_HEADER_TYPE"

# DATABASE MYSQL
DATABASE_NAME_USER = 'NAME_USER'
DATABASE_NAME_DB = "NAME_DB"
DATABASE_PASSWORD = "PASS_DB"
DATABASE_LOCALHOST = "NAME_LOCALHOST"
